### ISSUE TITLE
36bf8ea12ad2: Error downloading dependent layers

### ISSUE THREAD

**Issue by Ivan-Masli-GDP** [sequenceiq/docker-spark#33]
Hello, I ha ve tried to pull this docker image few times. However, I always get this error
36bf8ea12ad2: Error downloading dependent layers
Any idea why?

**Comment by biharitomi** [comment]
Hi,

I was able to pull the latest sequenceiq/spark docker image, but the id that you mentioned could not be found between the ids of dependent layers.

Which version of the image have you tried to pull?

Could you check the error is still exist?
Because I assume the problem related to the docker hub.

Br,
Tamas

**Comment by Ivan-Masli-GDP** [comment]
It seems you are right. I have tried to download again and it works this time
